config/routes.rb
Rails.application.routes.draw do

root :to =>'pages#home'
get 'home/about' => 'pages#about'

resources :users, :only => [:new, :create, :index]

get '/login' => 'session#new'
post '/login' => 'session#create'
delete '/login' => 'session#destroy'

resources :soundbags, :only => [:new, :create]

get '/samples' => 'samples#index'
get '/samples/instruments' => 'samples#instrument'
get '/samples/artists' => 'samples#artist'
get '/samples/instruments/:name'=> 'samples#instrumentsample', :as => 'instsample'

get '/samples/artists/:name'=> 'samples#artistsample', :as => 'artsample'

resources :artists
resources :instruments
resources :collections


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :samples
  has_and_belongs_to_many :instruments
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  has_many :samples
  has_and_belongs_to_many :artists
end

app/models/sample.rb
class Sample < ApplicationRecord
  belongs_to :instrument, :optional => true
  belongs_to :artist, :optional => true
  has_and_belongs_to_many :soundbags

  def self.search(search)
    if search
      where(["name LIKE ?","%#{:search}%"])
    else
      all
    end
  end
end

app/models/soundbag.rb
class Soundbag < ApplicationRecord
  belongs_to :user, :optional => true
  has_and_belongs_to_many :samples
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  has_many :soundbags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user



  private

  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present?
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end

  def check_for_admin
    redirect_to login_path unless (@current_user.present? && @current_user.admin?)
  end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
before_action :check_for_login

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    artist = Artist.create artist_params
    redirect_to artist
  end

  def edit
    @artist = Artist.find params[:id]
  end

  def update
    artist = Artist.find params[:id]
    artist.update artist_params
    redirect_to artist
  end

  def show
    @artist= Artist.find params[:id]
  end

  def destroy
    artist = Artist.find params[:id]
    artist.destroy
    redirect_to artists_path
  end

  private
    def artist_params
      params.require(:artist).permit(:name, :country, :image, :id, :instrument_id)
    end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :check_for_login
  
  def index
    @samples = Sample.all
  end

  def new
    @sample = Sample.new
  end

  def create
  sample = Sample.create sample_params
  redirect_to collections_path
  end

  def edit
    @sample = Sample.find params[:id]
  end

  def update
    sample = Sample.find params[:id]
    sample.update sample_params
    redirect_to collections_path
  end

  def show
    @sample= Sample.find params[:id]
  end

  def destroy
    sample = Sample.find params[:id]
    sample.destroy
    redirect_to collections_path
  end


  private
  def sample_params
  params.require(:sample).permit(:name, :BPM, :musicalkey, :artist_id, :instrument_id)
  end

end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
 before_action :check_for_login

def index
  @instruments = Instrument.all
end

def new
  @instrument = Instrument.new
end

def create
instrument = Instrument.create instrument_params
redirect_to instrument
end

def edit
  @instrument = Instrument.find params[:id]
end

def update
  instrument = Instrument.find params[:id]
  instrument.update instrument_params
  redirect_to instrument
end

def show
  @instrument= Instrument.find params[:id]
end

def destroy
  instrument = Instrument.find params[:id]
  instrument.destroy
  redirect_to instruments_path
end


private
def instrument_params
params.require(:instrument).permit(:name, :family, :geo, :image)
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :check_for_login


  def index
    @samples = Sample.all
      if params.present?
        @samples = Sample.where(["name LIKE ?","%#{params[:search]}%"])
      else
        render samples_path
      end
  end

  def instrument
    @instruments = Instrument.all
  end

  def artist
    @artists = Artist.all
  end

  def instrumentsample
    @instrument = Instrument.find_by :name => params[:name]
    @instrument_id = @instrument.id
    @samples = Sample.all.where(instrument_id: @instrument_id)
  end

  def artistsample
     @artist = Artist.find_by :name => params[:name]
     @artist_id = @artist.id
     @samples = Sample.all.where(artist_id: @artist_id)

  end


  private
  def search_result
    params.require(:sample).permit(:name, :country, :musicalkey, :family, :search)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

end

app/controllers/soundbags_controller.rb
class SoundbagsController < ApplicationController
  before_action :check_for_login
  
  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index]

  def index
    @users =User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/explores_helper.rb
module ExploresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/soundbags_helper.rb
module SoundbagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :required => true %>

  <%= f.label :country %>
  <%= f.text_field :country %>

  <%= f.label :image %>
  <%= f.url_field :image %>

  <%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1> Edit Artist </h1>

<%= render :partial => 'form' %>

app/views/artists/index.html.erb
<h1>All Artists</h1>

<% @artists.each do |artist| %>
  <%= image_tag artist.image, :class => "thumbnail" if artist.image.present?  %>

  <ul>
    <li>Name: <%= link_to artist.name, artist %> </li>
    <li>Country: <%= artist.country %></li>

  </ul>
<% end %>

app/views/artists/new.html.erb
<h1>Add New Artist</h1>
<%= render :partial => 'form' %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>

<p> Country: <%= @artist.country %> </p>
<p> ID: <%= @artist.id %> </p>

 <%= image_tag @artist.image, :class => "thumbnail" if @artist.image.present? %>



 <div class = "controls">
   <%= link_to 'Edit', edit_artist_path(@artist.id)%>
   <%= link_to 'Delete', @artist, :method => 'delete', :data => {:confirm => 'Good artists never die'}%>
 </div>

app/views/collections/_form.html.erb
<%= form_for @sample, :url => collections_path do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :required => true %>

  <%= f.label :BPM %>
  <%= f.text_field :BPM %>

  <%= f.label :musicalkey %>
  <%= f.text_field :musicalkey %>

  <%= f.label :artist_id %>
  <%= f.select :artist_id, Artist.pluck(:name, :id), :include_blank => true  %>

  <%= f.label :instrument_id %>
  <%= f.select :instrument_id, Instrument.pluck(:name, :id), :include_blank => true  %>

  <%= f.submit %>
<% end %>

app/views/collections/edit.html.erb
<h1> Edit Collection </h1>

<%= form_for @sample, method: :post, :url => collections_path do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :required => true %>

  <%= f.label :BPM %>
  <%= f.text_field :BPM %>

  <%= f.label :musicalkey %>
  <%= f.text_field :musicalkey %>

  <%= f.label :artist_id %>
  <%= f.select :artist_id, Artist.pluck(:name, :id), :include_blank => true  %>

  <%= f.label :instrument_id %>
  <%= f.select :instrument_id, Instrument.pluck(:name, :id), :include_blank => true  %>

  <%= f.submit %>
<% end %>

app/views/collections/index.html.erb
<h1>All Samples</h1>

<% @samples.each do |sample| %>
  <ul>
    <li>Name: <%= link_to sample.name, collection_path(sample.id)%> </li>
    <li>Key: <%= sample.musicalkey %></li>
    <% if sample.BPM.present? %>
    <li>BPM: <%= sample.BPM %></li>
    <% end %>
  </ul>

<% end %>

app/views/collections/new.html.erb
<h1>Add New Sample</h1>
<%= render :partial => 'form' %>

app/views/collections/show.html.erb
<h1><%= @sample.name %></h1>

<p> Family: <%= @sample.BPM %> </p>
<p> Country: <%= @sample.musicalkey %> </p>


 <div class = "controls">
   <%= link_to 'Edit', edit_collection_path(@sample.id)%>
  <%= link_to 'Delete', collection_path(@sample.id), :method => 'delete', :data => {:confirm => 'Are you sure ?'}%>
 </div>

app/views/instruments/_form.html.erb
<%= form_for @instrument do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :required => true %>

  <%= f.label :family %>
  <%= f.text_field :family %>

  <%= f.label :country %>
  <%= f.text_field :country %>

  <%= f.label :image %>
  <%= f.url_field :image %>

  <%= f.submit %>
<% end %>

app/views/instruments/edit.html.erb
<h1> Edit Instruments </h1>

<%= render :partial => 'form' %>

app/views/instruments/index.html.erb
<h1>All Instruments</h1>

<% @instruments.each do |instrument| %>
  <%= image_tag instrument.image, :class => "thumbnail" if instrument.image.present?  %>

  <ul>
    <li>Name: <%= link_to instrument.name, instrument %> </li>
    <li>family: <%= instrument.family %></li>
    <% if instrument.country.present? %>
    <li>Country: <%= instrument.country %></li>
    <% end %>
  </ul>

<% end %>

app/views/instruments/new.html.erb
<h1>Add New Instrument</h1>
<%= render :partial => 'form' %>

app/views/instruments/show.html.erb
<h1><%= @instrument.name %></h1>

<p>
  Family: <%= @instrument.family %>
</p>
<p>
  Country: <%= @instrument.country %>
</p>
<p>
  id: <%= @instrument.id %>
</p>

 <%= image_tag @instrument.image, :class => "thumbnail" if @instrument.image.present? %>

 <div class = "controls">
   <%= link_to 'Edit', edit_instrument_path(@instrument.id)%>
   <%= link_to 'Delete', @instrument, :method => 'delete', :data => {:confirm => 'Are you sure ?'}%>
 </div>

app/views/samples/artist.html.erb
<div class="artists-container">
  <h1> Artists </h1>
   <% @artists.each do |artist| %>
    <div class= "artist-container"> 
     <% if artist.image.present? %>
      <div class= "artist-img"> 
          <%= link_to image_tag(artist.image, :class => "thumbnail-img"), artsample_path(artist.name)%>
      </div>
      <% end %>
      <div class= "artist-info-container"> 
        <div class= "artist-info">
          <span>Name:</span> <%= artist.name %> <br>
          <span>Country:</span> <%= artist.country %> <br>
          <span>Instruments:</span> 
            <% artist.instruments.each do |instrument| %>
               <%= link_to instrument.name, instsample_path(instrument.name) %>
            <% end %>
        </div>
        <div class= "artist-description">
          <br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et possimus eligendi vero tempore minima, velit, ratione unde perferendis nulla quasi accusantium architecto cupiditate dolore sunt, porro accusamus nesciunt voluptatem magnam.
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/samples/artistsample.html.erb
<div class="artist-samples-container">
  <h2> <%= @artist.name %> </h2>
    <div class= "artist-sample-container"> 
     <% if @artist.image.present? %>
      <div class= "artist-img"> 
         <%= image_tag @artist.image, :class=> "thumbnail"  %>
      </div>
      <% end %>
      <div class= "artist-sample-info-container"> 
        <% @samples.each do |sample| %>
          <div class= "sample-info-container">
            <div class="sample-info">
              <ul>
                <li>
                  <span> Sample Name: </span> <%= sample.name %>
                </li>
                <li>
                  <span> Key: </span> <%= sample.musicalkey %>
                </li>
                <li>
                  <span> BPM: </span> <%= sample.BPM %> 
                </li>
              </ul>
            </div>
            <div>
                <audio class="audio-container" controls="controls" src="/assets/<%=sample.name%>.wav"></audio>
            </div>
          </div>
        <% end %>  
      </div>
    </div>
</div>

app/views/samples/index.html.erb
<div class="search">
  <%= form_tag samples_path, :method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag ("search"), :name => nil %>
  <% end %>
</div>

<div class="sample-header">
    <div class="sample-name"><strong>Name</strong> </div>
    <div class="instrument-name"><strong>Instrument</strong></div>
    <div class="artist-name"><strong>Artist</strong></div>
    <div class="key"><strong>Key</strong></div>
    <div class="bpm"><strong>BPM</strong></div>
    <div class="audio"><strong>Audio</strong></div>
</div>

<div class="samples-container">
  <% @samples.each do |sample| %>
    <div class="sample-container" style="background-color: #00000052;">
        <div class="sml-name">
          <%= sample.name %>
        </div>
        <div class="ins-name">
          <% if sample.instrument_id.present? %>
            <%= sample.instrument.name %>
          <% end %>
        </div>
        <div class="art-name">
          <% if sample.artist_id.present? %>
            <%= sample.artist.name %>
          <% end %>
        </div>
        <div class="sml-key">
          <%= sample.musicalkey %>
        </div>
        <div class="sml-bpm">
          <%= sample.BPM %>
        </div>
        <div class="sml-audio">
          <audio  class="audio-container" controls="controls" src="/assets/<%=sample.name%>.wav"></audio>
        </div>
    </div>
  <% end %>

</div>

app/views/samples/instrument.html.erb
<div class="instruments-container">
  <h1> Instruments </h1>
  <% @instruments.each do |instrument| %>
    <div class= "instrument-container"> 
    <% if instrument.image.present? %>
      <div class= "instrument-img"> 
          <%=link_to image_tag(instrument.image, :class => "thumbnail-img"), instsample_path(instrument.name)%>
      </div>
      <% end %>
      <div class= "instrument-info-container"> 
        <div class= "instrument-info">
          <span>Name:</span> <%= instrument.name%> <br>
          <span>Family:</span> <%= instrument.family %> <br>
          <span>Country:</span> <%= instrument.country %> <br>
        </div>
        <div class= "instrument-description">
          <br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et possimus eligendi vero tempore minima, velit, ratione unde perferendis nulla quasi accusantium architecto cupiditate dolore sunt, porro accusamus nesciunt voluptatem magnam.
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/samples/instrumentsample.html.erb
<div class="instrument-samples-container">
  <h2> <%= @instrument.name %> </h2>
    <div class= "instrument-sample-container"> 
     <% if @instrument.image.present? %>
      <div class= "instrument-img"> 
         <%= image_tag @instrument.image, :class => "thumbnail" %>
      </div>
      <% end %>
      <div class= "instrument-sample-info-container"> 
        <% @samples.each do |sample| %>
          <div class= "sample-info-container">
            <div class="sample-info">
              <ul>
                <li>
                  <span> Sample: </span> <%= sample.name %>
                </li>
                <li>
                  <span> Key: </span> <%= sample.musicalkey %>
                </li>
              </ul>
            </div>
            <div>
                <audio class="audio-container" controls="controls" src="/assets/<%=sample.name%>.wav"></audio>
            </div>
          </div>
        <% end %>  
      </div>
    </div>
</div>

app/views/session/new.html.erb
<div class="login-container">
  <h1> LOG IN TO YOUR SAMPLEAST ACCOUNT </h1>
  
  <%= form_tag login_path do %>
  
    <div class="form-group">
      <%= label_tag :email  %>
      <%= email_field_tag :email, nil, :class => "form-control" %>
    </div>
  
    <div class="form-group">
      <%= label_tag :password  %>
      <%= password_field_tag :password, nil ,:class => "form-control" %>
    </div>
  
    <%= submit_tag "Login", :class => "btn btn-dark btn-lg btn-block"  %>
  <% end  %>
  
  Don't have an acount? <%=link_to "SIGN UP NOW", new_user_path  %>
</div>

app/views/soundbags/new.html.erb
<h1> Collection </h1>
<p>Find me in app/views/soundbags/new.html.erb</p>

app/views/users/new.html.erb
<div class="signup-container"> 
  <h1>CREATE A NEW SAMPLEAST ACCOUNT</h1>
  
  <% if @user.errors.any? %>
    <ul>
      <% @user.errors.full_messages.each do |er| %>
       <li>
         <%= er %>
       </li>
       <% end %>
    </ul>
  <% end %>
  
  <%= form_for @user do |f| %>
    <div class="form-group" >
        <%= f.label :name %>
        <%= f.text_field :name, :required => true, :class=> "form-control" %>
    </div>
  
    <div class="form-group" >
      <%= f.label :email %>
      <%= f.email_field :email, :class=> "form-control" %>
    </div>
  
    <div class="form-group" >
      <%=f.label :password %>
      <%=f.password_field :password, :required =>true, :class=> "form-control" %>
    </div>
  
    <div class="form-group">
      <%=f.label :password_confirmation %>
      <%=f.password_field :password_confirmation, :required =>true, :class=> "form-control" %>
    </div>
  
  <%= f.submit "Create", :class => "btn btn-dark btn-lg btn-block" %>
    <% end %>
  
    Have an acount? <%=link_to "SIGN IN HERE", login_path  %>
</div>

app/views/users/userindex.html.erb
  <h1> Users Details </h1>
  
  <% @users.each do |user|  %>
    <p>
      <strong>Name:</strong><%= user.name %>
      <strong>Email:</strong> <%= user.email %>
    </p>
  <% end %>