config/routes.rb
Rails.application.routes.draw do

root :to =>'pages#home'
get 'home/about' => 'pages#about'

resources :users, :only => [:new, :create, :index]

get '/login' => 'session#new'
post '/login' => 'session#create'
delete '/login' => 'session#destroy'

resources :soundbags, :only => [:new, :create]

get '/samples' => 'samples#index'
get '/samples/instruments' => 'samples#instrument'
get '/samples/artists' => 'samples#artist'
get '/samples/instruments/:name'=> 'samples#instrumentsample', :as => 'instsample'

get '/samples/artists/:name'=> 'samples#artistsample', :as => 'artsample'

resources :artists
resources :instruments
resources :collections


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :samples
  has_and_belongs_to_many :instruments
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  has_many :samples
  has_and_belongs_to_many :artists
end

app/models/sample.rb
class Sample < ApplicationRecord
  belongs_to :instrument, :optional => true
  belongs_to :artist, :optional => true
  has_and_belongs_to_many :soundbags

  def self.search(search)
    if search
      where(["name LIKE ?","%#{:search}%"])
    else
      all
    end
  end
end

app/models/soundbag.rb
class Soundbag < ApplicationRecord
  belongs_to :user, :optional => true
  has_and_belongs_to_many :samples
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  has_many :soundbags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user



  private

  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present?
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end

  def check_for_admin
    redirect_to login_path unless (@current_user.present? && @current_user.admin?)
  end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
before_action :check_for_login

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    artist = Artist.create artist_params
    redirect_to artist
  end

  def edit
    @artist = Artist.find params[:id]
  end

  def update
    artist = Artist.find params[:id]
    artist.update artist_params
    redirect_to artist
  end

  def show
    @artist= Artist.find params[:id]
  end

  def destroy
    artist = Artist.find params[:id]
    artist.destroy
    redirect_to artists_path
  end

  private
    def artist_params
      params.require(:artist).permit(:name, :country, :image, :id, :instrument_id)
    end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :check_for_login
  
  def index
    @samples = Sample.all
  end

  def new
    @sample = Sample.new
  end

  def create
  sample = Sample.create sample_params
  redirect_to collections_path
  end

  def edit
    @sample = Sample.find params[:id]
  end

  def update
    sample = Sample.find params[:id]
    sample.update sample_params
    redirect_to collections_path
  end

  def show
    @sample= Sample.find params[:id]
  end

  def destroy
    sample = Sample.find params[:id]
    sample.destroy
    redirect_to collections_path
  end


  private
  def sample_params
  params.require(:sample).permit(:name, :BPM, :musicalkey, :artist_id, :instrument_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :check_for_login


  def index
    @samples = Sample.all
      if params.present?
        @samples = Sample.where(["name LIKE ?","%#{params[:search]}%"])
      else
        render samples_path
      end
  end

  def instrument
    @instruments = Instrument.all
  end

  def artist
    @artists = Artist.all
  end

  def instrumentsample
    @instrument = Instrument.find_by :name => params[:name]
    @instrument_id = @instrument.id
    @samples = Sample.all.where(instrument_id: @instrument_id)
  end

  def artistsample
     @artist = Artist.find_by :name => params[:name]
     @artist_id = @artist.id
     @samples = Sample.all.where(artist_id: @artist_id)

  end


  private
  def search_result
    params.require(:sample).permit(:name, :country, :musicalkey, :family, :search)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

end

app/controllers/soundbags_controller.rb
class SoundbagsController < ApplicationController
  before_action :check_for_login
  
  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index]

  def index
    @users =User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/explores_helper.rb
module ExploresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/soundbags_helper.rb
module SoundbagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sampleast</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class= "container">
     <nav class="navbar navbar-expand">
       <a class="navbar-brand"> <strong>SamplEast</strong></a>
       <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav mr-auto">
           <li class="nav-item">
             <%= link_to " Home", root_path %>
           </li>
           <% if @current_user.present? %>
             <% if @current_user.admin? %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                | Admin
                </a>

                <div class="dropdown-menu" >
                  <%= link_to "New Artist", new_artist_path %>
                  <div class="dropdown-divider"></div>
                  <%= link_to "All Artists", artists_path%>
                    <div class="dropdown-divider"></div>
                  <%= link_to "New Instrument", new_instrument_path %>
                    <div class="dropdown-divider"></div>
                  <%= link_to "All Instrument", instruments_path%>
                    <div class="dropdown-divider"></div>
                  <%= link_to "New Sample", new_collection_path %>
                  <div class="dropdown-divider"></div>
                  <%= link_to "All Samples", collections_path %>
                </div>
              </li>
            <% end %>

             <li class="nav-item">
               | <%= link_to "Samples ", samples_path %>
               | <%= link_to "Instruments ", samples_instruments_path %>
               | <%= link_to "Artists ", samples_artists_path %>
               | <%= link_to "Log out #{@current_user.email}", login_path, :method => 'delete'%>
             </li>
         <% else %>

            <li class="nav-item">
               | <%= link_to "About Us", home_about_path %>
               | <%= link_to "Sign up", new_user_path %>
               | <%= link_to "Log in", login_path %>
            </li>
         <% end %>
         </ul>
       </div>
     </nav>
        <%= yield %>
   </div>

  </body>
</html>

app/views/pages/about.html.erb
<br><h1> About SsamplEast </h1><br>

<div>

  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam, nam! Rem totam nobis dolore architecto itaque magni! Sunt sapiente nostrum, autem perferendis officiis facere, in veritatis nulla ea, obcaecati magni.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere recusandae enim obcaecati similique est. Molestias ea amet obcaecati ducimus iusto dolorum, maxime debitis dolorem fugiat temporibus voluptatem a, nam error!</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia voluptatem culpa est et, nesciunt voluptas dicta eveniet natus hic, iusto, ipsa veritatis magni! Eveniet provident laudantium officiis explicabo. Animi, consequuntur.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo ratione, tenetur! Tempora suscipit, quis! Dolores aperiam maiores tempora quam soluta consequatur excepturi cum, officia quas. Adipisci veritatis distinctio similique doloremque.</p>
  <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maiores, earum, fuga, corporis officiis cupiditate aliquam sequi praesentium nihil numquam sapiente neque quidem iste ab natus tempore dolore, dolorum aliquid.</p>
</div>

app/views/pages/home.html.erb
<div class="imgcontainer">
  <div class="img">
      <%= image_tag src= "/assets/SEbackground.png"%>
  </div>
</div>